export const SUBSCRIBE_TITLE_ADVANCED = 'Join Our Advanced Program';
export const SUBSCRIBE_TITLE_STANDART = 'Join Our Program';
export const SUBSCRIBE_BTN = 'subscribe';
export const UNSUBSCRIBE_BTN = 'unsubscribe';
export const SUBSCRIBE_BTN_ADVANCED = 'subscribe to Advanced Program';
export const STANDART_TYPE = 'standart';
export const ADVANCED_TYPE = 'advanced';
export const HIDDEN = 'hidden';
export const VALID_EMAIL_ENDINGS = ['gmail.com', 'outlook.com', 'yandex.ru'];
